# Generated by Django 5.2.1 on 2025-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.BinaryField(null=True, verbose_name='Зображення допису'),
        ),
    ]
